# Generated by Django 4.2.17 on 2025-01-12 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
        ("transaction_enrichment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(db_index=True, max_length=100, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="keyword",
            name="keyword",
            field=models.CharField(max_length=25, unique=True, verbose_name="Keyword"),
        ),
        migrations.AlterField(
            model_name="merchant",
            name="merchant_name",
            field=models.CharField(
                db_index=True, max_length=100, verbose_name="Merchant name"
            ),
        ),
        migrations.AlterField(
            model_name="transactionenrichment",
            name="transaction",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrichment",
                to="transactions.transaction",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("name", "type")},
        ),
    ]
