# Generated by Django 4.2.17 on 2025-01-12 01:33

from django.db import migrations, models

import common.validators


class Migration(migrations.Migration):

    dependencies = [
        (
            "transaction_enrichment",
            "0002_alter_category_name_alter_keyword_keyword_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="merchant",
            name="merchant_logo",
            field=models.URLField(
                blank=True,
                max_length=256,
                null=True,
                validators=[common.validators.valid_image_extension],
                verbose_name="Merchant logo",
            ),
        ),
    ]
