# Generated by Django 4.2.17 on 2025-01-12 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction_enrichment", "0003_alter_merchant_merchant_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keyword",
            name="merchant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="keywords",
                to="transaction_enrichment.merchant",
            ),
        ),
    ]
