# Generated by Django 5.1.4 on 2025-01-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction_enrichment", "0004_alter_keyword_merchant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keyword",
            name="keyword",
            field=models.CharField(
                db_index=True, max_length=25, verbose_name="Keyword"
            ),
        ),
    ]
